baseURL = "https://salv997.github.io/blog"
title = "SalvBlog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "SalvBlog"
description = "Ciao, sono Salv997 e questo è il mio blog."
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Salv997"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "2 January, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "favicon.ico"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

  [[params.profileMode.buttons]]
  name = "Posts"
  url = "posts"

  [[params.profileMode.buttons]]
  name = "Tags"
  url = "tags"

[params.homeInfoParams]
Title = "Benvenuti su SalvBlog 👋"
Content = "Il mio blog sul Graphic Design e Web Development"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = false
  hiddenInSingle = false

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categorie"
name = "categorie"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "website"
name = "Il mio sito"
url = "https://salv997.github.io"
weight = 30

[markup.highlight]
noClasses = false

[taxonomies]
   tag = "tags"
   category = "categories"


[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5